export const REQUEST_API = 'REQUEST_API';

export const RESET_ERROR = 'RESET_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const CODE_UPLOAD = 'CODE_UPLOAD';
export const GET_TSLINT_SUMMARY = 'GET_TSLINT_SUMMARY';
export const GET_TSLINT_SUMMARY_SUCCESS = 'GET_TSLINT_SUMMARY_SUCCESS';
export const GET_TSLINT_SUMMARY_FAILURE = 'GET_TSLINT_SUMMARY_FAILURE';